extension: Use Cogl.Color instead of Clutter.Color
The Clutter.Color API has been moved into Cogl.Color from Gnome Shell 47
forward, thus the extension currently doesn't load on GS 47:

    (gnome-shell:257518): Gjs-WARNING **: 12:22:22.519: JS ERROR: Extension system-monitor-next@paradoxxx.zero.gmail.com: TypeError: (intermediate value).Color.from_string is not a function
    color_from_string@file:///home/mgalgs/.local/share/gnome-shell/extensions/system-monitor-next@paradoxxx.zero.gmail.com/extension.js:149:34
    enable@file:///home/mgalgs/.local/share/gnome-shell/extensions/system-monitor-next@paradoxxx.zero.gmail.com/extension.js:2392:28
    _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:252:38
    loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:461:32
    async*_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:759:24
    async*_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:765:48
    _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:800:20
    async*init@resource:///org/gnome/shell/ui/extensionSystem.js:71:14
    _initializeUI@resource:///org/gnome/shell/ui/main.js:291:22
    start@resource:///org/gnome/shell/ui/main.js:164:11
    @resource:///org/gnome/shell/ui/init.js:11:47
    @resource:///org/gnome/shell/ui/init.js:21:20

Fix this by updating our color_from_string wrapper to use Cogl.Color when
it's available, while sticking to Clutter.Color when it's not.

Fixes #90

Suggested-by: sid <sidtosh4@gmail.com>