actions: syncer: Abort failed rebases
When the rebase fails the repo ends up in a mangled state. For example,
.github/sync-failed-template.md might not even be present in the source
directory after the failed rebase, which causes the "create-an-issue"
action to fail.

Fix this by aborting the rebase on failure so that the source directory
gets back to a sane state.

Fixes: https://github.com/mgalgs/gnome-shell-system-monitor-applet/runs/4106665884

    Error: File .github/sync-failed-template.md could not be found in your
    project's workspace. You may need the actions/checkout action to clone
    the repository first.